--- #YAML:1.0
name:               Finance-QuoteHist
version:            1.12
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Manip:         0
    HTML::TableExtract:  2.07
    HTTP::Request:       0
    LWP::UserAgent:      0
    MIME::Base64:        0
    Text::CSV_PP:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
